name: Makefile CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.7.4

    steps:
    - uses: actions/checkout@v2
      
    - name: Build Plugin
      run: make
      
    - name: Upload Plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin 3GX File
        path: Jisho.3gx
    
    - name: Upload Plugin ELF
      uses: actions/upload-artifact@v2
      with:
        name: Plugin ELF File
        path: Jisho.elf

    - name: Upload Dictionary
      uses: actions/upload-artifact@v2
      with:
        name: Dictionary TXT file
        path: JMdict_smol.txt

    - name: Create release if needed
      uses: softprops/action-gh-release@v1
      if: ${{startsWith(github.ref, 'refs/tags/') }}
      with:
          files: |
            Jisho.3gx
            Jisho.elf
            JMdict_smol.txt
